# Generated by Django 5.0.6 on 2024-06-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "hotel_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("hotel_name", models.CharField(max_length=100, unique=True)),
                ("hotel_class", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "review_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("review", models.TextField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="reviews.hotel",
                    ),
                ),
            ],
        ),
    ]
