# Generated by Django 5.0.6 on 2024-06-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_rename_hotel_review_hotel_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="hotel_id",
            new_name="hotel",
        ),
        migrations.RemoveField(
            model_name="review",
            name="review_id",
        ),
        migrations.AddField(
            model_name="review",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="value",
            field=models.CharField(max_length=10),
        ),
    ]
