# Generated by Django 5.0.6 on 2024-06-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_hotel_id_review_hotel_remove_review_review_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('positive', 'Positive'), ('very_positive', 'Very Positive'), ('negative', 'Negative'), ('very_negative', 'Very Negative')], max_length=20),
        ),
    ]
